version: "3.7"

services:
  webhook:
    image: hatamiarash7/webhook
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
    environment:
      - SECRET=changeme
      - DB_CONNECTION=mongodb://mongo:27017/webhook
      - SIGNATURE=X-Hub-Signature
      - LOG_LEVEL=debug
    networks:
      - webhook
    ports:
      - 0.0.0.0:4296:3000

  mongo:
    image: mongo:5.0.3
    restart: unless-stopped
    volumes:
      - mongo-data-1:/data/db
      - mongo-config-1:/data/configdb
    networks:
      - webhook

networks:
  webhook:
    external: false
    driver: bridge

volumes:
  mongo-data-1:
  mongo-config-1:
